# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [69]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],
    [4,5,6]
   ])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([    [[1,2,3],
        [4,5,6],
        [7,8,9]],
        [[10,11,12],
        [14,15,16],
        [13,17,18]
       ]
   ])


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [16]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape

(3,)

In [17]:
a1.ndim

1

In [18]:
a1.dtype


dtype('int32')

In [19]:
a1.size

3

In [20]:
type(a1)

numpy.ndarray

In [21]:
# Attributes of 2-dimensional array
a2.shape

(2, 3)

In [22]:
a2.size

6

In [23]:
a2.ndim

2

In [24]:
type(a2)

numpy.ndarray

In [27]:
a2.dtype

dtype('int32')

In [29]:
# Attributes of 3-dimensional array
a3.ndim

3

In [30]:
a3.size

18

In [31]:
a3.dtype

dtype('int32')

In [32]:
type(a3)

numpy.ndarray

In [33]:
a3.shape

(2, 3, 3)

In [38]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df= pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [58]:
# Create an array of shape (10, 2) with only ones
a4=np.ones((10,2),dtype= int)
a4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [56]:
a4.shape

(10, 2)

In [59]:
# Create an array of shape (7, 2, 3) of only zeros
a5=np.zeros((7,2,3), dtype=int)
a5


array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [60]:
a5.shape

(7, 2, 3)

In [6]:
# Create an array within a range of 0 and 100 with step 3
a6= np.arange(0,100,3)
a6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [9]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a7= np.random.randint(0,10,size=(7,2))
a7

array([[1, 9],
       [2, 0],
       [0, 1],
       [6, 2],
       [0, 7],
       [2, 5],
       [6, 5]])

In [16]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a8=np.random.rand(3,5)
a8

array([[0.37660413, 0.66261533, 0.84483913, 0.98089466, 0.92342437],
       [0.01961936, 0.072572  , 0.61639146, 0.09800134, 0.40188173],
       [0.27758011, 0.00570391, 0.14226306, 0.12868644, 0.75193345]])

In [29]:

# Set the random seed to 42
np.random.seed(42)
# Create a random array of numbers between 0 & 10 of size (4, 6)
a9=np.random.randint(10,size=(5,3))
a9

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [12]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
np.random.seed(3)
random_arr=np.random.randint(1,10,size=(3,7))
random_arr
# Find the unique numbers in the array you just created
#np.unique(random_arr)

array([[9, 4, 9, 9, 1, 6, 4],
       [6, 8, 7, 1, 5, 8, 9],
       [2, 7, 3, 3, 2, 4, 6]])

In [8]:
# Find the 0'th index of the latest array you created
a1[0]

1

In [13]:
# Get the first 2 rows of latest array you created
random_arr[:2]

array([[9, 4, 9, 9, 1, 6, 4],
       [6, 8, 7, 1, 5, 8, 9]])

In [14]:
# Get the first 2 values of the first 2 rows of the latest array
random_arr[:2,:2]

# Always remember the outer most value in size will repersent the inner most element in the arr

array([[9, 4],
       [6, 8]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr1= np.random.randint(1,9, size=(3,5))
ones=np.ones((3,5))
arr1,
sum=arr1+ones

In [19]:
# Add the two arrays together
arr1+ones

array([[4., 5., 6., 6., 5.],
       [5., 2., 9., 2., 2.],
       [2., 4., 4., 5., 9.]])

In [40]:
# Create another array of ones of shape (5, 3)
ones=np.ones((5,3))

In [42]:
# Try add the array of ones and the other most recent array together
#sum = ones + sum

ones.shape,sum.shape,sum

((5, 3),
 (3, 5),
 array([[4., 5., 6., 6., 5.],
        [5., 2., 9., 2., 2.],
        [2., 4., 4., 5., 9.]]))

In [46]:
ones=ones.reshape(5,3,1)
sum+ones

array([[[ 5.,  6.,  7.,  7.,  6.],
        [ 6.,  3., 10.,  3.,  3.],
        [ 3.,  5.,  5.,  6., 10.]],

       [[ 5.,  6.,  7.,  7.,  6.],
        [ 6.,  3., 10.,  3.,  3.],
        [ 3.,  5.,  5.,  6., 10.]],

       [[ 5.,  6.,  7.,  7.,  6.],
        [ 6.,  3., 10.,  3.,  3.],
        [ 3.,  5.,  5.,  6., 10.]],

       [[ 5.,  6.,  7.,  7.,  6.],
        [ 6.,  3., 10.,  3.,  3.],
        [ 3.,  5.,  5.,  6., 10.]],

       [[ 5.,  6.,  7.,  7.,  6.],
        [ 6.,  3., 10.,  3.,  3.],
        [ 3.,  5.,  5.,  6., 10.]]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
ones=np.ones((3,5))

In [25]:
# Subtract the new array of ones from the other most recent array
arr1-ones

array([[2., 3., 4., 4., 3.],
       [3., 0., 7., 0., 0.],
       [0., 2., 2., 3., 7.]])

In [28]:
# Multiply the ones array with the latest array
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [31]:
# Take the latest array to the power of 2 using '**'
a1,a1**2

(array([1, 2, 3]), array([1, 4, 9]))

In [32]:
# Do the same thing with np.square()
np.square(a1)

array([1, 4, 9])

In [33]:
# Find the mean of the latest array using np.mean()
a2,np.mean(a2)

(array([[1, 2, 3],
        [4, 5, 6]]),
 3.5)

In [34]:
# Find the maximum of the latest array using np.max()
a3,np.max(a3)

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [14, 15, 16],
         [13, 17, 18]]]),
 18)

In [35]:
# Find the minimum of the latest array using np.min()
np.min(a3)

1

## If youre working with numpy data use numpy method and if you are working with py data then use python data as it is faster 

In [37]:
# Find the standard deviation of the latest array
np.std(a3)

5.188127472091127

In [36]:
# Find the variance of the latest array
np.var(a3)

26.916666666666668

In [47]:
a1

array([1, 2, 3])

In [56]:
# Reshape the latest array to (3, 5, 1)
arr=np.ones((3,5))
arr.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [57]:
# Transpose the latest array
arr.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do? rows=col,col=rows

In [58]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
np.random.seed(0)
mat1 = np.random.randint(10,size=(3,3))
mat2 = np.random.randint(10,size=(3,2))
np.dot(mat1,mat2)

array([[ 44,  38],
       [126,  86],
       [ 58,  63]])

In [63]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
np.random.seed(3)
mat3 = np.random.randint(10,size=(4,3))
mat4 = np.random.randint(10,size=(4,3))

In [64]:
# Perform a dot product on the two newest arrays you created
 np.dot(mat3,mat4) gives error
#to fix it we take transpose of mat4


IndentationError: unexpected indent (2680351764.py, line 2)

It doesn't work. How would you fix it?

In [65]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
mat4=mat4.T
np.dot(mat3,mat4)

array([[ 60, 131,  72,  50],
       [ 48, 120,  64,  32],
       [ 66,  68,  54,  59],
       [ 82, 110,  78,  59]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [66]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a1,a2

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [70]:
# Compare the two arrays with '>'
a1>a2

array([[ True,  True,  True],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='
a1>=a2

In [71]:
# Find which elements of the first array are greater than 7
a1>7

array([False, False, False])

In [72]:
random_arr

array([[9, 4, 9, 9, 1, 6, 4],
       [6, 8, 7, 1, 5, 8, 9],
       [2, 7, 3, 3, 2, 4, 6]])

In [73]:
# Sort one of the arrays you just created in ascending order
np.sort(random_arr)


array([[1, 4, 4, 6, 9, 9, 9],
       [1, 5, 6, 7, 8, 8, 9],
       [2, 2, 3, 3, 4, 6, 7]])

In [75]:
# Sort the indexes of one of the arrays you just created
random_arr,np.argsort(random_arr)

(array([[9, 4, 9, 9, 1, 6, 4],
        [6, 8, 7, 1, 5, 8, 9],
        [2, 7, 3, 3, 2, 4, 6]]),
 array([[4, 1, 6, 5, 0, 2, 3],
        [3, 4, 0, 2, 1, 5, 6],
        [0, 4, 2, 3, 5, 6, 1]], dtype=int64))

In [77]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a3)

17

In [78]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a1)

0

In [80]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
random_arr,np.argmax(random_arr,axis=1)

(array([[9, 4, 9, 9, 1, 6, 4],
        [6, 8, 7, 1, 5, 8, 9],
        [2, 7, 3, 3, 2, 4, 6]]),
 array([0, 6, 1], dtype=int64))

In [81]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
random_arr,np.argmin(random_arr,axis=0)

(array([[9, 4, 9, 9, 1, 6, 4],
        [6, 8, 7, 1, 5, 8, 9],
        [2, 7, 3, 3, 2, 4, 6]]),
 array([2, 0, 2, 1, 0, 2, 0], dtype=int64))

In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.